import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import express from "express";
import multer from "multer";
const required = ["ADMIN_EMAIL", "ADMIN_PASSWORD", "ADMIN_SESSION_SECRET"];
function settings() { const missing = required.filter((key) => !process.env[key]); if (missing.length) throw new Error(`Missing server environment variables: ${missing.join(", ")}`); return { email: process.env.ADMIN_EMAIL, password: process.env.ADMIN_PASSWORD, secret: process.env.ADMIN_SESSION_SECRET }; }
const dataDir = process.env.SITE_DATA_DIR || path.join(process.cwd(), "site-data"), uploadDir = path.join(dataDir, "uploads"), configFile = path.join(dataDir, "site-images.json"); fs.mkdirSync(uploadDir, { recursive: true });
const read = () => { try { return JSON.parse(fs.readFileSync(configFile, "utf8")); } catch { return {}; } }, write = (data) => fs.writeFileSync(configFile, JSON.stringify(data, null, 2));
const token = (value) => crypto.createHmac("sha256", settings().secret).update(value).digest("base64url");
const isAdmin = (req) => { const raw = (req.headers.cookie || "").split(";").map((item) => item.trim()).find((item) => item.startsWith("glassco_admin="))?.slice(15); if (!raw) return false; const [payload, signature] = raw.split("."); if (!payload || !signature || !crypto.timingSafeEqual(Buffer.from(token(payload)), Buffer.from(signature))) return false; try { return JSON.parse(Buffer.from(payload, "base64url").toString()).exp > Date.now(); } catch { return false; } };
const protect = (req, res, next) => isAdmin(req) ? next() : res.status(401).json({ error: "Sign in required" });
const upload = multer({ storage: multer.diskStorage({ destination: uploadDir, filename: (_req, file, done) => done(null, `${Date.now()}-${crypto.randomBytes(5).toString("hex")}-${file.originalname.replace(/[^a-z0-9._-]/gi, "-")}`) }), limits: { fileSize: 12 * 1024 * 1024 }, fileFilter: (_req, file, done) => done(null, /^image\/(jpeg|png|webp|gif)$/.test(file.mimetype)) });
export function createAdminRouter() { const router = express.Router(); router.get("/site-images", (_req, res) => res.json(read())); router.post("/admin/login", (req, res) => { const config = settings(); if (req.body?.email !== config.email || typeof req.body?.password !== "string" || !crypto.timingSafeEqual(Buffer.from(req.body.password), Buffer.from(config.password))) return res.status(401).json({ error: "Invalid email or password" }); const payload = Buffer.from(JSON.stringify({ exp: Date.now() + 28800000 })).toString("base64url"); res.setHeader("Set-Cookie", `glassco_admin=${payload}.${token(payload)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800`); res.json({ ok: true }); }); router.post("/admin/logout", (_req, res) => { res.setHeader("Set-Cookie", "glassco_admin=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0"); res.json({ ok: true }); }); router.get("/admin/site-images", protect, (_req, res) => res.json(read())); router.post("/admin/site-images/:slot", protect, upload.single("image"), (req, res) => { if (!req.file) return res.status(400).json({ error: "Upload a JPG, PNG, WebP or GIF under 12 MB." }); const images = read(); images[req.params.slot] = `/site-uploads/${req.file.filename}`; write(images); res.json({ url: images[req.params.slot] }); }); router.use("/site-uploads", express.static(uploadDir, { maxAge: "1h" })); return router; }