/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesTougheningHeatStrengtheningRouteImport } from './routes/services.toughening-heat-strengthening'
import { Route as ServicesIguRouteImport } from './routes/services.igu'
import { Route as ServicesGlassProcessingRouteImport } from './routes/services.glass-processing'
import { Route as ProductsEnergyEfficientGlassRouteImport } from './routes/products.energy-efficient-glass'
import { Route as ProductsDigitalGlassPrintingRouteImport } from './routes/products.digital-glass-printing'
import { Route as ProductsDecorativeGlassRouteImport } from './routes/products.decorative-glass'
import { Route as ProductsAcousticGlassRouteImport } from './routes/products.acoustic-glass'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTougheningHeatStrengtheningRoute =
  ServicesTougheningHeatStrengtheningRouteImport.update({
    id: '/services/toughening-heat-strengthening',
    path: '/services/toughening-heat-strengthening',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIguRoute = ServicesIguRouteImport.update({
  id: '/services/igu',
  path: '/services/igu',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGlassProcessingRoute = ServicesGlassProcessingRouteImport.update({
  id: '/services/glass-processing',
  path: '/services/glass-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsEnergyEfficientGlassRoute =
  ProductsEnergyEfficientGlassRouteImport.update({
    id: '/products/energy-efficient-glass',
    path: '/products/energy-efficient-glass',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsDigitalGlassPrintingRoute =
  ProductsDigitalGlassPrintingRouteImport.update({
    id: '/products/digital-glass-printing',
    path: '/products/digital-glass-printing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsDecorativeGlassRoute = ProductsDecorativeGlassRouteImport.update({
  id: '/products/decorative-glass',
  path: '/products/decorative-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAcousticGlassRoute = ProductsAcousticGlassRouteImport.update({
  id: '/products/acoustic-glass',
  path: '/products/acoustic-glass',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products/acoustic-glass': typeof ProductsAcousticGlassRoute
  '/products/decorative-glass': typeof ProductsDecorativeGlassRoute
  '/products/digital-glass-printing': typeof ProductsDigitalGlassPrintingRoute
  '/products/energy-efficient-glass': typeof ProductsEnergyEfficientGlassRoute
  '/services/glass-processing': typeof ServicesGlassProcessingRoute
  '/services/igu': typeof ServicesIguRoute
  '/services/toughening-heat-strengthening': typeof ServicesTougheningHeatStrengtheningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products/acoustic-glass': typeof ProductsAcousticGlassRoute
  '/products/decorative-glass': typeof ProductsDecorativeGlassRoute
  '/products/digital-glass-printing': typeof ProductsDigitalGlassPrintingRoute
  '/products/energy-efficient-glass': typeof ProductsEnergyEfficientGlassRoute
  '/services/glass-processing': typeof ServicesGlassProcessingRoute
  '/services/igu': typeof ServicesIguRoute
  '/services/toughening-heat-strengthening': typeof ServicesTougheningHeatStrengtheningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products/acoustic-glass': typeof ProductsAcousticGlassRoute
  '/products/decorative-glass': typeof ProductsDecorativeGlassRoute
  '/products/digital-glass-printing': typeof ProductsDigitalGlassPrintingRoute
  '/products/energy-efficient-glass': typeof ProductsEnergyEfficientGlassRoute
  '/services/glass-processing': typeof ServicesGlassProcessingRoute
  '/services/igu': typeof ServicesIguRoute
  '/services/toughening-heat-strengthening': typeof ServicesTougheningHeatStrengtheningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/products/acoustic-glass'
    | '/products/decorative-glass'
    | '/products/digital-glass-printing'
    | '/products/energy-efficient-glass'
    | '/services/glass-processing'
    | '/services/igu'
    | '/services/toughening-heat-strengthening'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/products/acoustic-glass'
    | '/products/decorative-glass'
    | '/products/digital-glass-printing'
    | '/products/energy-efficient-glass'
    | '/services/glass-processing'
    | '/services/igu'
    | '/services/toughening-heat-strengthening'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/products/acoustic-glass'
    | '/products/decorative-glass'
    | '/products/digital-glass-printing'
    | '/products/energy-efficient-glass'
    | '/services/glass-processing'
    | '/services/igu'
    | '/services/toughening-heat-strengthening'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProductsAcousticGlassRoute: typeof ProductsAcousticGlassRoute
  ProductsDecorativeGlassRoute: typeof ProductsDecorativeGlassRoute
  ProductsDigitalGlassPrintingRoute: typeof ProductsDigitalGlassPrintingRoute
  ProductsEnergyEfficientGlassRoute: typeof ProductsEnergyEfficientGlassRoute
  ServicesGlassProcessingRoute: typeof ServicesGlassProcessingRoute
  ServicesIguRoute: typeof ServicesIguRoute
  ServicesTougheningHeatStrengtheningRoute: typeof ServicesTougheningHeatStrengtheningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/toughening-heat-strengthening': {
      id: '/services/toughening-heat-strengthening'
      path: '/services/toughening-heat-strengthening'
      fullPath: '/services/toughening-heat-strengthening'
      preLoaderRoute: typeof ServicesTougheningHeatStrengtheningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/igu': {
      id: '/services/igu'
      path: '/services/igu'
      fullPath: '/services/igu'
      preLoaderRoute: typeof ServicesIguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/glass-processing': {
      id: '/services/glass-processing'
      path: '/services/glass-processing'
      fullPath: '/services/glass-processing'
      preLoaderRoute: typeof ServicesGlassProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/energy-efficient-glass': {
      id: '/products/energy-efficient-glass'
      path: '/products/energy-efficient-glass'
      fullPath: '/products/energy-efficient-glass'
      preLoaderRoute: typeof ProductsEnergyEfficientGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/digital-glass-printing': {
      id: '/products/digital-glass-printing'
      path: '/products/digital-glass-printing'
      fullPath: '/products/digital-glass-printing'
      preLoaderRoute: typeof ProductsDigitalGlassPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/decorative-glass': {
      id: '/products/decorative-glass'
      path: '/products/decorative-glass'
      fullPath: '/products/decorative-glass'
      preLoaderRoute: typeof ProductsDecorativeGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/acoustic-glass': {
      id: '/products/acoustic-glass'
      path: '/products/acoustic-glass'
      fullPath: '/products/acoustic-glass'
      preLoaderRoute: typeof ProductsAcousticGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProductsAcousticGlassRoute: ProductsAcousticGlassRoute,
  ProductsDecorativeGlassRoute: ProductsDecorativeGlassRoute,
  ProductsDigitalGlassPrintingRoute: ProductsDigitalGlassPrintingRoute,
  ProductsEnergyEfficientGlassRoute: ProductsEnergyEfficientGlassRoute,
  ServicesGlassProcessingRoute: ServicesGlassProcessingRoute,
  ServicesIguRoute: ServicesIguRoute,
  ServicesTougheningHeatStrengtheningRoute:
    ServicesTougheningHeatStrengtheningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
