/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ServicesTougheningHeatStrengtheningRouteImport } from './routes/services.toughening-heat-strengthening'
import { Route as ServicesIguRouteImport } from './routes/services.igu'
import { Route as ServicesGlassProcessingRouteImport } from './routes/services.glass-processing'
import { Route as ServicesDigitalGlassPrintingRouteImport } from './routes/services.digital-glass-printing'
import { Route as ProductsSecurityGlassAssaultShieldRouteImport } from './routes/products.security-glass-assault-shield'
import { Route as ProductsLowIronGlassRouteImport } from './routes/products.low-iron-glass'
import { Route as ProductsEnergyEfficientGlassRouteImport } from './routes/products.energy-efficient-glass'
import { Route as ProductsDecorativeGlassRouteImport } from './routes/products.decorative-glass'
import { Route as ProductsClearLaminatedGlassRouteImport } from './routes/products.clear-laminated-glass'
import { Route as ProductsClearFloatGlassRouteImport } from './routes/products.clear-float-glass'
import { Route as ProductsAutomotiveGlassRouteImport } from './routes/products.automotive-glass'
import { Route as ProductsAcousticGlassRouteImport } from './routes/products.acoustic-glass'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTougheningHeatStrengtheningRoute =
  ServicesTougheningHeatStrengtheningRouteImport.update({
    id: '/services/toughening-heat-strengthening',
    path: '/services/toughening-heat-strengthening',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIguRoute = ServicesIguRouteImport.update({
  id: '/services/igu',
  path: '/services/igu',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGlassProcessingRoute = ServicesGlassProcessingRouteImport.update({
  id: '/services/glass-processing',
  path: '/services/glass-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDigitalGlassPrintingRoute =
  ServicesDigitalGlassPrintingRouteImport.update({
    id: '/services/digital-glass-printing',
    path: '/services/digital-glass-printing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsSecurityGlassAssaultShieldRoute =
  ProductsSecurityGlassAssaultShieldRouteImport.update({
    id: '/products/security-glass-assault-shield',
    path: '/products/security-glass-assault-shield',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsLowIronGlassRoute = ProductsLowIronGlassRouteImport.update({
  id: '/products/low-iron-glass',
  path: '/products/low-iron-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsEnergyEfficientGlassRoute =
  ProductsEnergyEfficientGlassRouteImport.update({
    id: '/products/energy-efficient-glass',
    path: '/products/energy-efficient-glass',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsDecorativeGlassRoute = ProductsDecorativeGlassRouteImport.update({
  id: '/products/decorative-glass',
  path: '/products/decorative-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsClearLaminatedGlassRoute =
  ProductsClearLaminatedGlassRouteImport.update({
    id: '/products/clear-laminated-glass',
    path: '/products/clear-laminated-glass',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsClearFloatGlassRoute = ProductsClearFloatGlassRouteImport.update({
  id: '/products/clear-float-glass',
  path: '/products/clear-float-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAutomotiveGlassRoute = ProductsAutomotiveGlassRouteImport.update({
  id: '/products/automotive-glass',
  path: '/products/automotive-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAcousticGlassRoute = ProductsAcousticGlassRouteImport.update({
  id: '/products/acoustic-glass',
  path: '/products/acoustic-glass',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/quote': typeof QuoteRoute
  '/terms': typeof TermsRoute
  '/products/acoustic-glass': typeof ProductsAcousticGlassRoute
  '/products/automotive-glass': typeof ProductsAutomotiveGlassRoute
  '/products/clear-float-glass': typeof ProductsClearFloatGlassRoute
  '/products/clear-laminated-glass': typeof ProductsClearLaminatedGlassRoute
  '/products/decorative-glass': typeof ProductsDecorativeGlassRoute
  '/products/energy-efficient-glass': typeof ProductsEnergyEfficientGlassRoute
  '/products/low-iron-glass': typeof ProductsLowIronGlassRoute
  '/products/security-glass-assault-shield': typeof ProductsSecurityGlassAssaultShieldRoute
  '/services/digital-glass-printing': typeof ServicesDigitalGlassPrintingRoute
  '/services/glass-processing': typeof ServicesGlassProcessingRoute
  '/services/igu': typeof ServicesIguRoute
  '/services/toughening-heat-strengthening': typeof ServicesTougheningHeatStrengtheningRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/quote': typeof QuoteRoute
  '/terms': typeof TermsRoute
  '/products/acoustic-glass': typeof ProductsAcousticGlassRoute
  '/products/automotive-glass': typeof ProductsAutomotiveGlassRoute
  '/products/clear-float-glass': typeof ProductsClearFloatGlassRoute
  '/products/clear-laminated-glass': typeof ProductsClearLaminatedGlassRoute
  '/products/decorative-glass': typeof ProductsDecorativeGlassRoute
  '/products/energy-efficient-glass': typeof ProductsEnergyEfficientGlassRoute
  '/products/low-iron-glass': typeof ProductsLowIronGlassRoute
  '/products/security-glass-assault-shield': typeof ProductsSecurityGlassAssaultShieldRoute
  '/services/digital-glass-printing': typeof ServicesDigitalGlassPrintingRoute
  '/services/glass-processing': typeof ServicesGlassProcessingRoute
  '/services/igu': typeof ServicesIguRoute
  '/services/toughening-heat-strengthening': typeof ServicesTougheningHeatStrengtheningRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/quote': typeof QuoteRoute
  '/terms': typeof TermsRoute
  '/products/acoustic-glass': typeof ProductsAcousticGlassRoute
  '/products/automotive-glass': typeof ProductsAutomotiveGlassRoute
  '/products/clear-float-glass': typeof ProductsClearFloatGlassRoute
  '/products/clear-laminated-glass': typeof ProductsClearLaminatedGlassRoute
  '/products/decorative-glass': typeof ProductsDecorativeGlassRoute
  '/products/energy-efficient-glass': typeof ProductsEnergyEfficientGlassRoute
  '/products/low-iron-glass': typeof ProductsLowIronGlassRoute
  '/products/security-glass-assault-shield': typeof ProductsSecurityGlassAssaultShieldRoute
  '/services/digital-glass-printing': typeof ServicesDigitalGlassPrintingRoute
  '/services/glass-processing': typeof ServicesGlassProcessingRoute
  '/services/igu': typeof ServicesIguRoute
  '/services/toughening-heat-strengthening': typeof ServicesTougheningHeatStrengtheningRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/certifications'
    | '/contact'
    | '/gallery'
    | '/quote'
    | '/terms'
    | '/products/acoustic-glass'
    | '/products/automotive-glass'
    | '/products/clear-float-glass'
    | '/products/clear-laminated-glass'
    | '/products/decorative-glass'
    | '/products/energy-efficient-glass'
    | '/products/low-iron-glass'
    | '/products/security-glass-assault-shield'
    | '/services/digital-glass-printing'
    | '/services/glass-processing'
    | '/services/igu'
    | '/services/toughening-heat-strengthening'
    | '/products/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/certifications'
    | '/contact'
    | '/gallery'
    | '/quote'
    | '/terms'
    | '/products/acoustic-glass'
    | '/products/automotive-glass'
    | '/products/clear-float-glass'
    | '/products/clear-laminated-glass'
    | '/products/decorative-glass'
    | '/products/energy-efficient-glass'
    | '/products/low-iron-glass'
    | '/products/security-glass-assault-shield'
    | '/services/digital-glass-printing'
    | '/services/glass-processing'
    | '/services/igu'
    | '/services/toughening-heat-strengthening'
    | '/products'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/certifications'
    | '/contact'
    | '/gallery'
    | '/quote'
    | '/terms'
    | '/products/acoustic-glass'
    | '/products/automotive-glass'
    | '/products/clear-float-glass'
    | '/products/clear-laminated-glass'
    | '/products/decorative-glass'
    | '/products/energy-efficient-glass'
    | '/products/low-iron-glass'
    | '/products/security-glass-assault-shield'
    | '/services/digital-glass-printing'
    | '/services/glass-processing'
    | '/services/igu'
    | '/services/toughening-heat-strengthening'
    | '/products/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CertificationsRoute: typeof CertificationsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  QuoteRoute: typeof QuoteRoute
  TermsRoute: typeof TermsRoute
  ProductsAcousticGlassRoute: typeof ProductsAcousticGlassRoute
  ProductsAutomotiveGlassRoute: typeof ProductsAutomotiveGlassRoute
  ProductsClearFloatGlassRoute: typeof ProductsClearFloatGlassRoute
  ProductsClearLaminatedGlassRoute: typeof ProductsClearLaminatedGlassRoute
  ProductsDecorativeGlassRoute: typeof ProductsDecorativeGlassRoute
  ProductsEnergyEfficientGlassRoute: typeof ProductsEnergyEfficientGlassRoute
  ProductsLowIronGlassRoute: typeof ProductsLowIronGlassRoute
  ProductsSecurityGlassAssaultShieldRoute: typeof ProductsSecurityGlassAssaultShieldRoute
  ServicesDigitalGlassPrintingRoute: typeof ServicesDigitalGlassPrintingRoute
  ServicesGlassProcessingRoute: typeof ServicesGlassProcessingRoute
  ServicesIguRoute: typeof ServicesIguRoute
  ServicesTougheningHeatStrengtheningRoute: typeof ServicesTougheningHeatStrengtheningRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/toughening-heat-strengthening': {
      id: '/services/toughening-heat-strengthening'
      path: '/services/toughening-heat-strengthening'
      fullPath: '/services/toughening-heat-strengthening'
      preLoaderRoute: typeof ServicesTougheningHeatStrengtheningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/igu': {
      id: '/services/igu'
      path: '/services/igu'
      fullPath: '/services/igu'
      preLoaderRoute: typeof ServicesIguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/glass-processing': {
      id: '/services/glass-processing'
      path: '/services/glass-processing'
      fullPath: '/services/glass-processing'
      preLoaderRoute: typeof ServicesGlassProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/digital-glass-printing': {
      id: '/services/digital-glass-printing'
      path: '/services/digital-glass-printing'
      fullPath: '/services/digital-glass-printing'
      preLoaderRoute: typeof ServicesDigitalGlassPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/security-glass-assault-shield': {
      id: '/products/security-glass-assault-shield'
      path: '/products/security-glass-assault-shield'
      fullPath: '/products/security-glass-assault-shield'
      preLoaderRoute: typeof ProductsSecurityGlassAssaultShieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/low-iron-glass': {
      id: '/products/low-iron-glass'
      path: '/products/low-iron-glass'
      fullPath: '/products/low-iron-glass'
      preLoaderRoute: typeof ProductsLowIronGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/energy-efficient-glass': {
      id: '/products/energy-efficient-glass'
      path: '/products/energy-efficient-glass'
      fullPath: '/products/energy-efficient-glass'
      preLoaderRoute: typeof ProductsEnergyEfficientGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/decorative-glass': {
      id: '/products/decorative-glass'
      path: '/products/decorative-glass'
      fullPath: '/products/decorative-glass'
      preLoaderRoute: typeof ProductsDecorativeGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/clear-laminated-glass': {
      id: '/products/clear-laminated-glass'
      path: '/products/clear-laminated-glass'
      fullPath: '/products/clear-laminated-glass'
      preLoaderRoute: typeof ProductsClearLaminatedGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/clear-float-glass': {
      id: '/products/clear-float-glass'
      path: '/products/clear-float-glass'
      fullPath: '/products/clear-float-glass'
      preLoaderRoute: typeof ProductsClearFloatGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/automotive-glass': {
      id: '/products/automotive-glass'
      path: '/products/automotive-glass'
      fullPath: '/products/automotive-glass'
      preLoaderRoute: typeof ProductsAutomotiveGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/acoustic-glass': {
      id: '/products/acoustic-glass'
      path: '/products/acoustic-glass'
      fullPath: '/products/acoustic-glass'
      preLoaderRoute: typeof ProductsAcousticGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CertificationsRoute: CertificationsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  QuoteRoute: QuoteRoute,
  TermsRoute: TermsRoute,
  ProductsAcousticGlassRoute: ProductsAcousticGlassRoute,
  ProductsAutomotiveGlassRoute: ProductsAutomotiveGlassRoute,
  ProductsClearFloatGlassRoute: ProductsClearFloatGlassRoute,
  ProductsClearLaminatedGlassRoute: ProductsClearLaminatedGlassRoute,
  ProductsDecorativeGlassRoute: ProductsDecorativeGlassRoute,
  ProductsEnergyEfficientGlassRoute: ProductsEnergyEfficientGlassRoute,
  ProductsLowIronGlassRoute: ProductsLowIronGlassRoute,
  ProductsSecurityGlassAssaultShieldRoute:
    ProductsSecurityGlassAssaultShieldRoute,
  ServicesDigitalGlassPrintingRoute: ServicesDigitalGlassPrintingRoute,
  ServicesGlassProcessingRoute: ServicesGlassProcessingRoute,
  ServicesIguRoute: ServicesIguRoute,
  ServicesTougheningHeatStrengtheningRoute:
    ServicesTougheningHeatStrengtheningRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
