/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesTougheningHeatStrengtheningRouteImport } from './routes/services.toughening-heat-strengthening'
import { Route as ServicesIguRouteImport } from './routes/services.igu'
import { Route as ServicesGlassProcessingRouteImport } from './routes/services.glass-processing'
import { Route as ServicesDigitalGlassPrintingRouteImport } from './routes/services.digital-glass-printing'
import { Route as ProductsEnergyEfficientGlassRouteImport } from './routes/products.energy-efficient-glass'
import { Route as ProductsDecorativeGlassRouteImport } from './routes/products.decorative-glass'
import { Route as ProductsAcousticGlassRouteImport } from './routes/products.acoustic-glass'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTougheningHeatStrengtheningRoute =
  ServicesTougheningHeatStrengtheningRouteImport.update({
    id: '/services/toughening-heat-strengthening',
    path: '/services/toughening-heat-strengthening',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIguRoute = ServicesIguRouteImport.update({
  id: '/services/igu',
  path: '/services/igu',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGlassProcessingRoute = ServicesGlassProcessingRouteImport.update({
  id: '/services/glass-processing',
  path: '/services/glass-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDigitalGlassPrintingRoute =
  ServicesDigitalGlassPrintingRouteImport.update({
    id: '/services/digital-glass-printing',
    path: '/services/digital-glass-printing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsEnergyEfficientGlassRoute =
  ProductsEnergyEfficientGlassRouteImport.update({
    id: '/products/energy-efficient-glass',
    path: '/products/energy-efficient-glass',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsDecorativeGlassRoute = ProductsDecorativeGlassRouteImport.update({
  id: '/products/decorative-glass',
  path: '/products/decorative-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAcousticGlassRoute = ProductsAcousticGlassRouteImport.update({
  id: '/products/acoustic-glass',
  path: '/products/acoustic-glass',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/quote': typeof QuoteRoute
  '/terms': typeof TermsRoute
  '/products/acoustic-glass': typeof ProductsAcousticGlassRoute
  '/products/decorative-glass': typeof ProductsDecorativeGlassRoute
  '/products/energy-efficient-glass': typeof ProductsEnergyEfficientGlassRoute
  '/services/digital-glass-printing': typeof ServicesDigitalGlassPrintingRoute
  '/services/glass-processing': typeof ServicesGlassProcessingRoute
  '/services/igu': typeof ServicesIguRoute
  '/services/toughening-heat-strengthening': typeof ServicesTougheningHeatStrengtheningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/quote': typeof QuoteRoute
  '/terms': typeof TermsRoute
  '/products/acoustic-glass': typeof ProductsAcousticGlassRoute
  '/products/decorative-glass': typeof ProductsDecorativeGlassRoute
  '/products/energy-efficient-glass': typeof ProductsEnergyEfficientGlassRoute
  '/services/digital-glass-printing': typeof ServicesDigitalGlassPrintingRoute
  '/services/glass-processing': typeof ServicesGlassProcessingRoute
  '/services/igu': typeof ServicesIguRoute
  '/services/toughening-heat-strengthening': typeof ServicesTougheningHeatStrengtheningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/quote': typeof QuoteRoute
  '/terms': typeof TermsRoute
  '/products/acoustic-glass': typeof ProductsAcousticGlassRoute
  '/products/decorative-glass': typeof ProductsDecorativeGlassRoute
  '/products/energy-efficient-glass': typeof ProductsEnergyEfficientGlassRoute
  '/services/digital-glass-printing': typeof ServicesDigitalGlassPrintingRoute
  '/services/glass-processing': typeof ServicesGlassProcessingRoute
  '/services/igu': typeof ServicesIguRoute
  '/services/toughening-heat-strengthening': typeof ServicesTougheningHeatStrengtheningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/certifications'
    | '/contact'
    | '/gallery'
    | '/quote'
    | '/terms'
    | '/products/acoustic-glass'
    | '/products/decorative-glass'
    | '/products/energy-efficient-glass'
    | '/services/digital-glass-printing'
    | '/services/glass-processing'
    | '/services/igu'
    | '/services/toughening-heat-strengthening'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/certifications'
    | '/contact'
    | '/gallery'
    | '/quote'
    | '/terms'
    | '/products/acoustic-glass'
    | '/products/decorative-glass'
    | '/products/energy-efficient-glass'
    | '/services/digital-glass-printing'
    | '/services/glass-processing'
    | '/services/igu'
    | '/services/toughening-heat-strengthening'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/certifications'
    | '/contact'
    | '/gallery'
    | '/quote'
    | '/terms'
    | '/products/acoustic-glass'
    | '/products/decorative-glass'
    | '/products/energy-efficient-glass'
    | '/services/digital-glass-printing'
    | '/services/glass-processing'
    | '/services/igu'
    | '/services/toughening-heat-strengthening'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CertificationsRoute: typeof CertificationsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  QuoteRoute: typeof QuoteRoute
  TermsRoute: typeof TermsRoute
  ProductsAcousticGlassRoute: typeof ProductsAcousticGlassRoute
  ProductsDecorativeGlassRoute: typeof ProductsDecorativeGlassRoute
  ProductsEnergyEfficientGlassRoute: typeof ProductsEnergyEfficientGlassRoute
  ServicesDigitalGlassPrintingRoute: typeof ServicesDigitalGlassPrintingRoute
  ServicesGlassProcessingRoute: typeof ServicesGlassProcessingRoute
  ServicesIguRoute: typeof ServicesIguRoute
  ServicesTougheningHeatStrengtheningRoute: typeof ServicesTougheningHeatStrengtheningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/toughening-heat-strengthening': {
      id: '/services/toughening-heat-strengthening'
      path: '/services/toughening-heat-strengthening'
      fullPath: '/services/toughening-heat-strengthening'
      preLoaderRoute: typeof ServicesTougheningHeatStrengtheningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/igu': {
      id: '/services/igu'
      path: '/services/igu'
      fullPath: '/services/igu'
      preLoaderRoute: typeof ServicesIguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/glass-processing': {
      id: '/services/glass-processing'
      path: '/services/glass-processing'
      fullPath: '/services/glass-processing'
      preLoaderRoute: typeof ServicesGlassProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/digital-glass-printing': {
      id: '/services/digital-glass-printing'
      path: '/services/digital-glass-printing'
      fullPath: '/services/digital-glass-printing'
      preLoaderRoute: typeof ServicesDigitalGlassPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/energy-efficient-glass': {
      id: '/products/energy-efficient-glass'
      path: '/products/energy-efficient-glass'
      fullPath: '/products/energy-efficient-glass'
      preLoaderRoute: typeof ProductsEnergyEfficientGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/decorative-glass': {
      id: '/products/decorative-glass'
      path: '/products/decorative-glass'
      fullPath: '/products/decorative-glass'
      preLoaderRoute: typeof ProductsDecorativeGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/acoustic-glass': {
      id: '/products/acoustic-glass'
      path: '/products/acoustic-glass'
      fullPath: '/products/acoustic-glass'
      preLoaderRoute: typeof ProductsAcousticGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CertificationsRoute: CertificationsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  QuoteRoute: QuoteRoute,
  TermsRoute: TermsRoute,
  ProductsAcousticGlassRoute: ProductsAcousticGlassRoute,
  ProductsDecorativeGlassRoute: ProductsDecorativeGlassRoute,
  ProductsEnergyEfficientGlassRoute: ProductsEnergyEfficientGlassRoute,
  ServicesDigitalGlassPrintingRoute: ServicesDigitalGlassPrintingRoute,
  ServicesGlassProcessingRoute: ServicesGlassProcessingRoute,
  ServicesIguRoute: ServicesIguRoute,
  ServicesTougheningHeatStrengtheningRoute:
    ServicesTougheningHeatStrengtheningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
